### ISSUE TITLE
Issue in Module 3

### ISSUE THREAD

**Issue by srushti-714** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#11]
Module 3: Get Started with Power Apps
Lab: Canvas App, Part 2
Task: 03 
Step: 04,05

The DisplayMode property expression is throwing an error
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/55180169/88949432-d94cfd80-d2b0-11ea-8646-b182d75b6054.png)

Task : 04
Steps:02,04

The Onselect property expression is throwing an error like 'Active Start' does not exists
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/55180169/88949597-1618f480-d2b1-11ea-9efc-4e2e23e6ef19.png)

**Comment by alwweb** [comment]
@srushti-714   I no longer have my environment where I tested everything, but for Task 4 step 4, the directions I have are Patch([@Visits], Visit, ...  rather than what you have above.  I don't remember having a problem with step 2.  I noted everywhere that my steps differed from the directions, or at least I thought I did.

For task 3 step 4 and 5 at the top, mine worked and looked exactly like yours and the lab steps as far as I can tell.  The only thing that I can think of is that your entity and attributes in CDS were spelled slightly different from what is in the book, or you have an extra space somewhere.  I would start with the Actual Start column since it is underlined in both. #

**Comment by chandlersyal** [comment]
It looks like there is an additional exclamation mark before your second "IsBlank" that is not needed. Did you copy and paste from the code block? 
If(!IsBlank(Visit) 
&& Visit.Status = 'Status (Visits)'.Active
&& IsBlank(Visit.'Actual Start'),
    DisplayMode.Edit,
    DisplayMode.Disabled
)

If you copy and paste directly, these both should work fine.
