### ISSUE TITLE
Mail Connector Issues for Flow Exercise (Module 4, Exercise 1)

### ISSUE THREAD

**Issue by JJGriffin** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#47]
# Module: 4
#### Step: 11

Description of issue

The student gets the following error when checking the Flow to confirm that it has run successfully:

![image](https://user-images.githubusercontent.com/24753554/140032535-7be6064d-31bf-42f1-ab55-7cdf56655ad2.png)

This issue is observable on any new trial tenant. The workaround I would suggest is that the student instead sets up a connection to Outlook using their MOD Administrator credentials, and use this connector to send out the email instead.

Repro steps:

1. Complete Exercise 1, Task 2 up to step 11
2. Check the flow run and the above error should be visible.

**Comment by JJGriffin** [comment]
Just to add, the second exercise in this lab also uses the same Mail connector.

**Comment by chandlersyal** [comment]
Apologies for the delay. Are you or your students still experiencing this issue?

**Comment by JJGriffin** [comment]
Yes, this issue still occurs for any new tenant where this exercise is completed on.

**Comment by chandlersyal** [comment]
Thank you for your confirmation. I just updated the steps. The users should choose the Office 365 Outlook connector instead of the Mail connector moving forward. Let me know if you have any further issues. 

Search for *mail*, select **Office 365 Outlook** connector and **Send an email (V2)** action (updated for both instances of using Mail connector).
