### ISSUE TITLE
'Failed to create entity' error in Module 2/Exer 2/Task 2 or 3

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#66]
# Module: 02
## Lab/Demo: 01
Exercise 2
#### Step: 00

Description of issue

In Module 2/Exercise 2/Tasks 2 and/or 3 when attempting to create either the Building or Visit table, you may experience the error:

![image](https://user-images.githubusercontent.com/49700217/147158185-f99c6dc0-7b7e-4752-b9d3-b2b7113077ae.png)

Repro steps:

I have reproed the error several times using a standard ALH VM + Tenant, and has also been reported by Instructors and MCTs taking the course.

It appears that this behavior may not appear consistently in _every_ attmept to create one or the other tables, but reasonably often that I feel it probably is a good idea to include some instructions detailing a way to examine running processes to insure they are completed before proceeding and/or if one rec'vs that error.

In each case where I was able to repro the error, I went to the 'See history' link, then looked to see if there were any solutons still 'running'.  I would consistently get the error while the 'MicrosoftPortalDependencies' was running, but once it finished, and result status was 'success', the errors went away:

![image](https://user-images.githubusercontent.com/49700217/147158244-130f3404-e3d1-4c12-b003-55e1d2edb71c.png)

**Comment by chandlersyal** [comment]
I can add some details on what to do if a user experiences this error, if we feel like this is a prevalent issue not due to timing. This error happens because the portal provisioning process (Lab 0) is running at the same time as the user is trying to complete steps in Lab 1. It’s typically why we split the labs this way, so that the users provision the portal and then have some instruction break before moving on to the next lab. The suggested course timing is to do Lab 0 followed by Mod 2 instruction and then Lab 1. 

Please see the Trainer Prep Guide for the full suggested schedule. If you hear that users are following this suggested order and are still running into this issue, I am happy to add a note in Lab 1.
